name: project1
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8091:8080
    depends_on:
      - database
    networks:
      - backend

  api:
    container_name: api
    build: api
    volumes:
      - api:/app
    networks:
      - backend
      - frontend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env

  web-app:
    container_name: web-app
    build: web-app
    ports:
      - 8090:5000
    volumes:
      - web-app:/app
    networks:
      - frontend
    depends_on:
      - database
      - api

volumes:
  db_data:
  web-app:
  api:


networks:
  backend:
    name: backend
  frontend:
    name: frontend
